
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yeexu_qt
 */
public class Librarian extends javax.swing.JFrame {

    /**
     * Creates new form Librarian
     */
    public Librarian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libName = new javax.swing.JLabel();
        libID = new javax.swing.JLabel();
        bookCategory = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        clkStatus = new javax.swing.JLabel();
        bStatus = new javax.swing.JButton();
        bAddMember = new javax.swing.JButton();
        bAddCategory = new javax.swing.JButton();
        bDeleteCateory = new javax.swing.JButton();
        bAddBook = new javax.swing.JButton();
        bEditBook = new javax.swing.JButton();
        bDeleteBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookCategory.setText("Book Category");

        status.setText("Status");

        bAddMember.setText("Add Member");

        bAddCategory.setText("Add Category");
        bAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddCategoryActionPerformed(evt);
            }
        });

        bDeleteCateory.setText("Delete Category");

        bAddBook.setText("Add Book");

        bEditBook.setText("Edit Book");

        bDeleteBook.setText("Delete Book");

        jScrollPane1 = new JScrollPane(t);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(libName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(status)
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(clkStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(bookCategory)))
                .addGap(46, 46, 46)
                .addComponent(bStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAddMember, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAddCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bDeleteCateory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAddBook, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bEditBook, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bDeleteBook, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bAddBook, bAddCategory, bAddMember, bDeleteBook, bDeleteCateory, bEditBook});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(libName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(status)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(bAddMember)
                        .addGap(18, 18, 18)
                        .addComponent(bAddCategory)
                        .addGap(18, 18, 18)
                        .addComponent(bDeleteCateory)
                        .addGap(18, 18, 18)
                        .addComponent(bAddBook)
                        .addGap(18, 18, 18)
                        .addComponent(bEditBook)
                        .addGap(18, 18, 18)
                        .addComponent(bDeleteBook))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clkStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookCategory))
                            .addComponent(bStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddCategoryActionPerformed
        // TODO add your handling code here:
        AddCategory addc = new AddCategory();
        addc.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_bAddCategoryActionPerformed
    /*//constructor to get new category
    public Librarian(int i,String newc){
        initComponents();
        System.out.println(newc);
        if (i==1){
            
        }
        tr.reload();
    }*/
    
    private static TreeFromTextFile tr = new TreeFromTextFile();
    JTree t = tr.getTree();
    
    public void reload(){
        /*DefaultTreeModel model =(DefaultTreeModel)t.getModel().getRoot();
        model.reload((TreeNode)model.getRoot());
        /*TreeModel model = t.getModel();
        model.valueForPathChanged(new TreePath(model.getRoot()), "javax.swing");
        ((DefaultTreeModel) model).reload();*/
        
        TreeFromTextFile tr = new TreeFromTextFile();
        JTree t = tr.getTree();
        JScrollPane jScrollPane1 = new JScrollPane(t);
        Class<?> addCate=TreeFromTextFile.class;
        addCate.getClassLoader();
        Class<?> these=Librarian.class;
        these.getClassLoader();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarian().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddBook;
    private javax.swing.JButton bAddCategory;
    private javax.swing.JButton bAddMember;
    private javax.swing.JButton bDeleteBook;
    private javax.swing.JButton bDeleteCateory;
    private javax.swing.JButton bEditBook;
    private javax.swing.JButton bStatus;
    private javax.swing.JLabel bookCategory;
    private javax.swing.JLabel clkStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel libID;
    private javax.swing.JLabel libName;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
